blank_issues_enabled: false
contact_links:
  - name: "ğŸŒ Community / ç¤¾ç¾¤è®¨è®º"
    about: "Join in our Telegram channel. / åŠ å…¥åˆ°ç”µæŠ¥é¢‘é“å¯»æ±‚æ›´å¤šå¸®åŠ©ã€‚"
    url: "https://t.me/+ZXphsppxUg41YmVl"
  - name: "ğŸ“– FAQ / å¸¸è§é—®é¢˜"
    about: "Please take a look to FAQs. / è¯·å…ˆé˜…è¯»æ–‡æ¡£ FAQï¼Œå¯èƒ½ä¼šæœ‰ä½ éœ€è¦çš„ç­”æ¡ˆã€‚"
    url: "https://docs.certimate.me/docs/reference/faq"
